package com.tv.settings.beans

enum class Language(val string: String, val cnName: String) {
    GERMAN("de-DE", "德语"),
    ENGLISH_AUSTRALIA("en-AU", "英语 (澳大利亚)"),
    ENGLISH_UK("en-GB", "英语 (英国)"),
    ENGLISH_INDIA("en-IN", "英语 (印度)"),
    ENGLISH_US("en-US", "英语 (美国)"),
    SPANISH_US("es-US", "西班牙语 (美国)"),
    FRENCH_FRANCE("fr-FR", "法语 (法国)"),
    HINDI_INDIA("hi-IN", "印地语"),
    PORTUGUESE_BRAZIL("pt-BR", "葡萄牙语 (巴西)"),
    ARABIC_GENERAL("ar-XA", "阿拉伯语"),
    SPANISH_SPAIN("es-ES", "西班牙语 (西班牙)"),
    FRENCH_CANADA("fr-CA", "法语 (加拿大)"),
    INDONESIAN_INDONESIA("id-ID", "印度尼西亚语"),
    ITALIAN_ITALY("it-IT", "意大利语"),
    JAPANESE_JAPAN("ja-JP", "日语"),
    TURKISH_TURKEY("tr-TR", "土耳其语"),
    VIETNAMESE_VIETNAM("vi-VN", "越南语"),
    BENGALI_INDIA("bn-IN", "孟加拉语"),
    GUJARATI_INDIA("gu-IN", "古吉拉特语"),
    KANNADA_INDIA("kn-IN", "卡纳达语"),
    MALAYALAM_INDIA("ml-IN", "马拉雅拉姆语"),
    MARATHI_INDIA("mr-IN", "马拉地语"),
    TAMIL_INDIA("ta-IN", "泰米尔语"),
    TELUGU_INDIA("te-IN", "泰卢固语"),
    DUTCH_NETHERLANDS("nl-NL", "荷兰语"),
    KOREAN_KOREA("ko-KR", "韩语"),
    MANDARIN_CHINA("cmn-CN", "中文 (普通话)"),
    POLISH_POLAND("pl-PL", "波兰语"),
    RUSSIAN_RUSSIA("ru-RU", "俄语"),
    THAI_THAILAND("th-TH", "泰语");
}